Task6
MyHubAlex/react_blog pull request #2
Opened 2017-05-08 10:23 UTC by MyHubAlex

2017-05-08 10:25 UTC, index01d commented
node_modules нужно добавить в gitignore

2017-05-08 10:25 UTC, index01d commented
20 000 файлов в PR:) Никак не проверить

2017-05-09 05:20 UTC, index01d requested changes
лучше импортировать конкретные функции из lodash и использовать их без  _ (`import { map } from 'lodash/collection`) + нужно устранить console.log'и из репозитория

Также в проекте нужно либо везде использовать JSX, либо везде его не использовать.

2017-05-09 05:22 UTC, index01d commented
вместо относительных путей при импорте `import BlogPage from '../containers/BlogPageContainer';` лучше использовать абсолютные `import BlogPage from 'containers/BlogPageContainer';`. Исключение – частные модули относящиеся только к текущему компоненту и хранящиеся с ним в одной директории (./Dependency или ./widgets/Dependency)

2017-05-11 17:31 UTC, MyHubAlex commented
Внес изменения плюс вместе с 7 заданием.

2017-05-12 08:20 UTC, index01d approved these changes

2017-05-12 09:00 UTC, merged